### ISSUE TITLE
Esto es un issue

### ISSUE THREAD

**Issue by Frozen-Burrito** [DonitaCosmica/Proyecto-Movil-Final#1]
Necesito ayuda de @DonitaCosmica  y el @VaquitaCosmica

**Comment by Frozen-Burrito** [comment]
Acutalization

**Comment by Frozen-Burrito** [comment]
Otro comentario

**Comment by Frozen-Burrito** [comment]
A @VaquitaCosmica  no le han dado su GitHub pro por estudiante. No lo han contactado, no lo quieren.

**Comment by VaquitaCosmica** [comment]
Abro hilo en twitter
twitter.com/dany_hernandez/post=1231232?c12
ya valiste madre lo voy a publicar en pornhub para que me apoyen

**Comment by Frozen-Burrito** [comment]
Me comentan que no reciben reclamos de gente que no tiene #PRO

**Comment by Frozen-Burrito** [comment]
Manco

**Comment by VaquitaCosmica** [comment]
manco tu pendejo

**Comment by VaquitaCosmica** [comment]
Perdon ferchito, me altere, tqm
